### ISSUE TITLE
Visual Studio Crashes when opening solution with Audit.net

### ISSUE THREAD

**Issue by jainaashish** [OSSIndex/audit.net#15]
Every time a solution is loaded it crashes immediately when audit.net is enabled. More details can be found here - https://developercommunity.visualstudio.com/content/problem/99433/visual-studio-crashes-when-opening-solution-3.html 

This has already been fixed via https://github.com/OSSIndex/audit.net/commit/cf24459deca6a7898d5248cc22242ad98a89c38b so please take care of this.

**Comment by OSSIndex-Admin** [comment]
Thanks for the report. It appears we have not kept the GitHub tags up to date with what has been uploaded to the marketplace. I believe that the code you have linked is already in the uploaded release. I am currently upgrading Visual Studio and will try to reproduce the problem. Even if I cannot reproduce the issue I will re-spin a release since the previous was generated using a pre-release version of Visual Studio 2017.

I'll do my best to resolve this as quickly as possible.

**Comment by OSSIndex-Admin** [comment]
I have reproduced the issue and am working on a solution.

**Comment by OSSIndex-Admin** [comment]
It seems that the problem resides in the code which checks to see if a project supports Nuget packages. The used method throws exceptions of various sorts depending on the status of the project. Originally we were only checking for InvalidOperationException, but it appears that other project types can cause other exceptions.

For that reason we now catch any exception, like so:
```
            try
            {
                // FIXME: This should not happen
                if (project == null) return false;
                IVsPackageInstallerServices locator = ServiceLocator.GetInstance<IVsPackageInstallerServices>();
                // FIXME: This should not happen
                if (locator == null) return false;
                locator.IsPackageInstalled(project, "__dummy__");
                return true;
            }
            catch (InvalidOperationException)
            {
                return false;
            }
            catch (Exception)
            {
                // FIXME: A variety of project types which do not work with the IsPackageInstalled method will throw exceptions of various sorts.
                // FIXME: Surely there is a better way to check for Nuget support?
                return false;
            }
```

We kept the original catch, since that is the one we expected. This new catch should prevent any crashing, anyhow, even if it results in the plugin not working in some situations. I am generating a new distribution now.

**Comment by OSSIndex-Admin** [comment]
What is curious is that I know this was working in earlier versions, including the 2017RC. It seems that something changed since then.
